const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const R=__dirname,D=JSON.parse(fs.readFileSync(path.join(R,'tour-data.json'),'utf8')),E=JSON.parse(fs.readFileSync(path.join(R,'excursions.json'),'utf8'));
const S=JSON.parse(fs.readFileSync(path.join(R,'scenery-guide.json'),'utf8'));
assert.equal(S.order.length,405);
assert.equal(new Set(S.order).size,405);
assert.deepEqual(new Set(S.order),new Set([...Object.keys(D.airports),...Object.keys(E.points)]));
assert.equal(Object.values(S.airports).filter(g=>g.mode==='owned').length,39);
assert.deepEqual(Object.keys(S.products).sort(),['LMML','NZAA','NZWN','SPZO','TFFJ','VHHH']);
assert.deepEqual(Object.keys(S.freeware).sort(),['EKVG','EYVI','LROP','VNKT','VOCI','VQPR','YPKG']);
assert(Object.entries(S.freeware).every(([code,f])=>S.airports[code].mode==='freeware'&&f.rating>=4.8&&f.reviews>=20&&f.downloads>=10000&&f.compatibility&&f.dependencies&&!D.inventory.some(a=>a.icao===code)));
assert.equal(S.airports.LNMC.mode,'verify');assert(S.freewareConsidered.some(r=>r.codes.includes('FMEE')));
assert(Object.keys(S.products).every(code=>!D.inventory.some(a=>a.icao===code)));
assert.equal(D.airports.VQPR.scenery,'base');assert.equal(D.airports.MHTG.scenery,'base');
assert.equal(S.airports.TFFJ.baseline,'base');assert.equal(S.airports.SCRM.mode,'verify');
assert(Object.values(S.airports).every(g=>g.links.every(l=>l[1].startsWith('https://'))));
assert.equal(E.excursions.length,19);
assert.equal(E.excursions.filter(e=>e.categoryVisit!==false).length,16);
assert.equal(E.excursions.filter(e=>e.profile==='DHC6').length,1);
assert.equal(E.excursions.filter(e=>e.profile==='H160').length,18);
assert(E.excursions.every(e=>e.profile===(e.country==='AQ'?'DHC6':'H160')));
assert(E.excursions.find(e=>e.id==='BONUS-EGLC').profile==='H160');
assert(E.excursions.find(e=>e.id==='TV').profile==='H160');
assert(E.excursions.find(e=>e.id==='TV').fuelNote.includes('Rotuma'));
assert(E.excursions.filter(e=>e.profile==='H160').flatMap(e=>e.legs).every(l=>l.nm<=269));
assert(E.excursions.find(e=>e.country==='AQ').legs.every(l=>l.nm>480));
assert(E.excursions.every(e=>e.aircraftReason));
const baseline=JSON.parse(fs.readFileSync(path.join(R,'route-baseline.json'),'utf8'));
assert.deepEqual(D.legs.map(l=>[l.id,l.from,l.to]),baseline.main);
assert.deepEqual(E.excursions.map(e=>[e.id,e.afterLeg,e.route,e.legs.map(l=>[l.id,l.from,l.to])]),baseline.side);
assert.equal(S.airports.TNCM.mode,'included');
assert.equal(S.auditSummary.screenedAirports,405);
assert.equal(S.auditSummary.productReviewedAirports,81);
assert.equal(S.auditSummary.reviewedFreewareProducts,71);
assert(Object.values(S.airports).every(g=>g.comparison.searched&&g.comparison.freewareConclusion&&g.comparison.paywareConclusion));
assert(Object.values(S.airports).filter(g=>g.comparison.fsacReadable).length===S.auditSummary.fsacReadable);
assert(Object.values(S.airports).every(g=>g.comparison.freeware.every(f=>f.stage!=='Empfohlen'||g.mode==='freeware')));
assert(!S.airports.FSIA.reason.includes('verhindern eine Kaufempfehlung')); // obsolete terrain reports must not be treated as current facts
assert.equal(E.excursions.flatMap(e=>e.legs).length,46);
assert.deepEqual(E.bonusOwnedAirports,['EGLC','KSEZ','NZMF']);
assert(E.bonusOwnedAirports.every(k=>D.inventory.some(i=>i.icao===k&&!i.inRoute)));
assert(E.excursions.every(e=>e.fuelNote&&!e.decisionPending));
const planned=new Set(Object.values(D.airports).map(a=>a.country));
for(const e of E.excursions){assert.equal(e.route[0],e.route.at(-1));assert.equal(D.legs[e.afterLeg-1].to,e.anchor);assert.equal(E.points[e.target].country,e.country);planned.add(e.country);for(const l of e.legs){assert.equal(l.over2h,l.airMin>120);assert(l.nm>0);assert(E.points[l.from]&&E.points[l.to]);}}
assert.equal(planned.size,245);assert(D.countries.every(c=>planned.has(c.code)));
const elements=new Map(),el=s=>{if(!elements.has(s))elements.set(s,{innerHTML:'',textContent:'',value:s==='#countryFilter'?'all':'',addEventListener(){},classList:{contains(){return false}}});return elements.get(s)};
el('#excursionData').textContent=JSON.stringify(E);
el('#sceneryData').textContent=JSON.stringify(S);
const stored=new Map([['tour',JSON.stringify({done:[1,2],xDone:['X-GG-1']})]]);
const c={D,A:D.airports,B:JSON.parse(fs.readFileSync(path.join(R,'briefings.json'),'utf8')),state:{done:new Set([1,2])},storageKey:'tour',storageOK:true,$:el,document:{addEventListener(){},querySelectorAll(){return []}},ResizeObserver:class{observe(){}},localStorage:{getItem:k=>stored.get(k),setItem:(k,v)=>stored.set(k,v)},esc:s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;'),normalize:s=>String(s).toLowerCase(),fmt:n=>String(n),hm:m=>`${Math.floor(m/60)}:${String(m%60).padStart(2,'0')}`,renderProgress(){},renderRows(){},renderDetail(){},showView(){},download(){},toast(){}};
vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(R,'d3.min.js'),'utf8'),c);vm.runInContext(fs.readFileSync(path.join(R,'topojson.min.js'),'utf8'),c);
vm.runInContext(fs.readFileSync(path.join(R,'excursions-ui.js'),'utf8'),c);
vm.runInContext(fs.readFileSync(path.join(R,'scenery-ui.js'),'utf8'),c);
vm.runInContext('renderCoverage()',c);
assert.equal((el('#exceptions').innerHTML.match(/<article /g)||[]).length,19);
assert.equal((el('#exceptions').innerHTML.match(/data-xdone=/g)||[]).length,46);
assert.equal((el('#countryRows').innerHTML.match(/<tr>/g)||[]).length,245);
assert(el('#exceptions').innerHTML.includes('Geschlossen · fiktiver Besuch'));
const rows=vm.runInContext('allJourney()',c);assert.equal(rows.length,449);assert.equal(rows[0].from,'EDLV');assert.equal(rows.at(-1).to,'EDLV');for(let i=1;i<rows.length;i++)assert.equal(rows[i-1].to,rows[i].from);
assert.equal(new Set(rows.map(l=>l.id)).size,449);
vm.runInContext("state.xDone.add('X-GG-2');saveAll()",c);assert.deepEqual(JSON.parse(stored.get('tour')),{done:[1,2],xDone:['X-GG-1','X-GG-2'],retiredXDone:[]});
assert.equal((el('#journeyRows').innerHTML.match(/data-journeyid=/g)||[]).length,449);
el('#journeyFleet').value='DHC6';vm.runInContext('renderJourney()',c);assert.equal((el('#journeyRows').innerHTML.match(/data-journeyid=/g)||[]).length,2);
el('#journeyStatus').value='long';vm.runInContext('renderJourney()',c);assert.equal((el('#journeyRows').innerHTML.match(/data-journeyid=/g)||[]).length,2);
el('#journeyFleet').value='all';el('#journeyStatus').value='done';vm.runInContext('renderJourney()',c);assert.equal((el('#journeyRows').innerHTML.match(/data-journeyid=/g)||[]).length,4);
el('#journeyStatus').value='all';
el('#countryFilter').value='exception';vm.runInContext('renderCountryRows()',c);assert.equal((el('#countryRows').innerHTML.match(/<tr>/g)||[]).length,16);
el('#countryFilter').value='all';el('#countrySearch').value='lljr';vm.runInContext('renderCountryRows()',c);assert.equal((el('#countryRows').innerHTML.match(/<tr>/g)||[]).length,1);
const W=JSON.parse(fs.readFileSync(path.join(R,'world.json'),'utf8')),world=c.topojson.feature(W,W.objects.countries);
for(const e of E.excursions)for(const w of [320,800]){const pts=[...new Set(e.route)].map(k=>[E.points[k].lon,E.points[k].lat]),proj=c.d3.geoMercator().fitExtent([[55,60],[w-95,300]],{type:'MultiPoint',coordinates:pts}),geo=c.d3.geoPath(proj);for(const pt of pts){const p=proj(pt);assert(p.every(Number.isFinite));assert(p[0]>=54.99&&p[0]<=w-94.99&&p[1]>=59.99&&p[1]<=300.01)}for(const f of world.features){const p=geo(f);assert(!p||!p.match(/NaN|Infinity/));}}
console.log('PASS: 245 categories; 449 continuous closed legs; 19 cards/46 checkboxes; fleet/status filters; stored progress; finite map paths at desktop/mobile widths. DOM rendering not visually tested.');
// Exercise the actual embedded app initialization, including legacy progress migration.
const nodes=new Map(),node=s=>{if(!nodes.has(s))nodes.set(s,{innerHTML:'',textContent:'',value:({'#countryFilter':'all','#filter':'all','#scope':'chapter'})[s]||'',style:{},clientWidth:0,clientHeight:0,addEventListener(){},scrollIntoView(){},classList:{contains(){return false},toggle(){}}});return nodes.get(s)};
for(const [id,name] of [['tourData','tour-data.json'],['worldData','world.json'],['briefingData','briefings.json'],['excursionData','excursions.json'],['sceneryData','scenery-guide.json'],['debriefData','../debriefings.json']])node('#'+id).textContent=fs.readFileSync(path.join(R,name),'utf8');
const memory=new Map([['volanta-worldtour-edlv-2026-09-v1',JSON.stringify({done:[1,2],xDone:['X-GG-1']})]]);
const full={document:{getElementById:id=>node('#'+id),querySelector:node,querySelectorAll:()=>[],addEventListener(){}},localStorage:{getItem:k=>memory.get(k),setItem:(k,v)=>memory.set(k,v)},d3:c.d3,topojson:c.topojson,ResizeObserver:class{observe(){}},setTimeout,clearTimeout,window:{scrollTo(){}},requestAnimationFrame(){},matchMedia(){return {matches:false}}};
vm.createContext(full);vm.runInContext(fs.readFileSync(path.join(R,'app-check.js'),'utf8'),full);
assert(node('#stats').innerHTML.includes('245<em> / 245'));
assert.equal((node('#countryRows').innerHTML.match(/<tr>/g)||[]).length,245);
assert(node('#xProgress').textContent.startsWith('1 / 46'));
assert.equal((node('#expeditionGrid').innerHTML.match(/<article /g)||[]).length,7);
assert.equal((node('#journeyRows').innerHTML.match(/data-journeyid=/g)||[]).length,449);
assert(node('#stats').innerHTML.includes('39<em> / 44'));
assert.equal((node('#inventory').innerHTML.match(/Im H160-Ausflug/g)||[]).length,3);
assert.equal((node('#sceneryRows').innerHTML.match(/data-scenery-row=/g)||[]).length,405);
assert.equal((node('#sceneryShortlist').innerHTML.match(/<article /g)||[]).length,6);
assert.equal((node('#freewareShortlist').innerHTML.match(/<article /g)||[]).length,7);
assert(node('#comparisonSummary').innerHTML.includes('405 / 405'));
assert.equal(S.auditSummary.reviewedPaywareAirports,21);
assert.equal(S.auditSummary.fsacReadable,164);
assert.equal(S.auditSummary.fsacUnavailable,241);
assert.equal((node('#manufacturerRows').innerHTML.match(/<tr>/g)||[]).length,7);
assert(node('#manufacturerRows').innerHTML.includes('Captain7'));
assert(S.airports.EDDK.recommendation.includes('Jo Erlend'));
assert(S.airports.FACT.comparison.payware.some(p=>p.verdict&&p.verdict.includes('12-Meter')));
assert(!S.considered.NZWN);
assert(S.products.LMML.caveat.includes('World Update IX'));
assert(S.manufacturers.every(m=>m.codes.every(code=>S.airports[code])));
node('#sceneryDepth').value='Produktprüfung';vm.runInContext('renderScenery()',full);
assert.equal((node('#sceneryRows').innerHTML.match(/data-scenery-row=/g)||[]).length,81);
node('#sceneryDepth').value='Suchabgleich';vm.runInContext('renderScenery()',full);
assert.equal((node('#sceneryRows').innerHTML.match(/data-scenery-row=/g)||[]).length,324);
node('#sceneryDepth').value='all';
node('#sceneryFilter').value='freeware';vm.runInContext('renderScenery()',full);
assert.equal((node('#sceneryRows').innerHTML.match(/data-scenery-row=/g)||[]).length,7);
assert(node('#sceneryRows').innerHTML.includes('85 Bewertungen'));assert(node('#sceneryRows').innerHTML.includes('Airbus-MCDU'));
node('#sceneryFilter').value='buy';vm.runInContext('renderScenery()',full);
assert.equal((node('#sceneryRows').innerHTML.match(/data-scenery-row=/g)||[]).length,6);
node('#sceneryFilter').value='owned';vm.runInContext('renderScenery()',full);
assert.equal((node('#sceneryRows').innerHTML.match(/data-scenery-row=/g)||[]).length,39);
vm.runInContext("openScenery('TFFJ')",full);
assert.equal((node('#sceneryRows').innerHTML.match(/data-scenery-row=/g)||[]).length,1);
assert(node('#sceneryRows').innerHTML.includes('SLH Sim Designs'));
node('#sceneryReset').onclick();
assert.equal((node('#sceneryRows').innerHTML.match(/data-scenery-row=/g)||[]).length,405);
vm.runInContext('toggleDone(3)',full);
assert.deepEqual(JSON.parse(memory.get('volanta-worldtour-edlv-2026-09-v1')),{done:[1,2,3],xDone:['X-GG-1'],retiredXDone:[]});
console.log('PASS: full embedded app initializes; existing main and excursion progress survives startup and main-leg edits.');

(async()=>{
  // A prior completed direct flight must not mark its new stopovers as flown.
  const backup={tour:'EDLV-2026-09-v1',total:403,done:[1,2],xDone:['X-GG-1','X-TV-1','X-TF-2']};
  await node('#backupFile').onchange({target:{files:[{text:async()=>JSON.stringify(backup)}],value:'backup.json'}});
  const migrated=JSON.parse(memory.get('volanta-worldtour-edlv-2026-09-v1'));
  assert.deepEqual(migrated,{done:[1,2],xDone:['X-GG-1'],retiredXDone:['X-TV-1','X-TF-2']});
  assert.equal(node('#retiredDetails').hidden,false);
  assert(node('#retiredRows').innerHTML.includes('NFFN'));
  let exported;
  full.download=(name,body,type)=>{exported={name,body,type}};
  node('#backupExport').onclick();
  const saved=JSON.parse(exported.body);assert.deepEqual(saved.retiredXDone,migrated.retiredXDone);
  node('#journeyCsv').onclick();
  const csv=exported.body;assert(csv.startsWith('\ufeff'));assert.equal(csv.split('\r\n').length,450);assert(csv.includes('Flügeltank-Transfer'));
  assert(csv.includes('Szenerie_Empfehlung'));assert(csv.includes('SLH Sim Designs'));assert(csv.includes('iniBuilds · Hong Kong'));
  node('#sceneryCsv').onclick();assert.equal(exported.body.split('\r\n').length,406);assert(exported.body.includes('Prueftiefe'));
  assert(exported.body.includes('Freeware_Downloads_ca'));assert(exported.body.includes('Bibliotheken_Installation'));assert(exported.body.includes('KapilGyawali'));
  assert(exported.body.includes('Payware_Kandidaten_und_Urteil'));assert(exported.body.includes('Photogrammetrie'));assert(exported.body.includes('Moa Point'));assert(exported.body.includes('Freeware_Kandidaten_und_Urteil'));assert(exported.body.includes('FSAddonCompare_ausgelesen'));assert(exported.body.includes('rekinowy'));
  const unchanged=memory.get('volanta-worldtour-edlv-2026-09-v1');
  await node('#backupFile').onchange({target:{files:[{text:async()=>JSON.stringify({...backup,xDone:['nonexistent']})}],value:'bad.json'}});
  assert.equal(memory.get('volanta-worldtour-edlv-2026-09-v1'),unchanged);
  console.log('PASS: legacy side-leg migration preserves completed replaced routes; JSON round trip; complete CSV with fuel notes; invalid backups leave progress intact.');
  console.log('PASS: all 405 airports in search comparison; 81 locations with product review; seven evidence-backed freeware entries; six unowned optional purchases; honest portal gaps; owned/included distinctions; depth filters/deep links; full CSV exports; H160 preferred and Twin Otter only Antarctica.');
})().catch(e=>{console.error(e);process.exitCode=1});
