const X=JSON.parse($('#excursionData').textContent),XA=X.points,XL=X.excursions.flatMap(e=>e.legs),xIDs=new Set(XL.map(l=>l.id));
let xSelected=X.excursions[0].id;
const retiredIDs=new Set((X.retiredLegs||[]).map(l=>l.id));
state.xDone=new Set();state.retiredXDone=new Set();
function restoreXProgress(saved){state.xDone=new Set((saved.xDone||[]).filter(id=>xIDs.has(id)));state.retiredXDone=new Set([...(saved.xDone||[]),...(saved.retiredXDone||[])].filter(id=>retiredIDs.has(id)))}
try{restoreXProgress(JSON.parse(localStorage.getItem(storageKey)||'{}'))}catch(e){storageOK=false}
function saveAll(){try{localStorage.setItem(storageKey,JSON.stringify({done:[...state.done],xDone:[...state.xDone],retiredXDone:[...state.retiredXDone]}))}catch(e){storageOK=false}renderProgress();renderXProgress();renderJourney();if(typeof renderDebriefs==='function')renderDebriefs();for(const box of document.querySelectorAll('[data-xdone]'))box.checked=state.xDone.has(box.dataset.xdone)}
function renderXProgress(){if($('#xProgress'))$('#xProgress').textContent=`${state.xDone.size} / ${XL.length} Ausflugs-Legs lokal geflogen · keine automatische Volanta-Synchronisierung`}
function renderFleet(){
 $('#fleetStrip').innerHTML=[['HAUPTROUTE','Fenix A320',`${D.legs.length} Legs · CFM Sharklets · deine großen Verbindungen`],['HELIKOPTER','Airbus H160',`${X.excursions.filter(e=>e.profile==='H160').length} Ausflüge · Heliports, Küsten und Gebirgstäler`],['ANTARKTIS-EXPEDITION','Twin Otter',`${X.excursions.filter(e=>e.profile==='DHC6').length} Ausflug · nur die lange Drake-Passage`]].map(t=>`<article class="fleet-tile"><div class="kicker">${t[0]}</div><b>${t[1]}</b><p>${t[2]}</p></article>`).join('');
 $('#fleetLogistics').textContent=X.logistics;
}
function renderCoverage(){const main=D.countries.filter(c=>c.status==='main').length,special=D.countries.filter(c=>c.status==='special').length;
 $('#coverageSummary').innerHTML=`<article><strong style="color:var(--teal)">${main}</strong><p>Kategorien in der A320-Hauptroute. Auch hier sind Anflug- und Leistungsbriefings nötig.</p></article><article><strong style="color:var(--gold)">+ ${special}</strong><p>Mit A320 im fiktiven Sonderbetrieb: US Minor Outlying Islands, Britisches Territorium im Indischen Ozean und Saint Helena via Ascension.</p></article><article><strong style="color:var(--purple)">+ ${X.excursions.filter(e=>e.categoryVisit!==false).length} = 245</strong><p>Zusätzliche Kategorien mit einer Twin-Otter- und fünfzehn H160-Schleifen. Drei weitere Ausflüge nutzen eigene Szenerien in bereits abgedeckten Ländern. Jeder Ausflug kehrt zum A320 zurück.</p></article>`;
 $('#xSelect').innerHTML=X.excursions.map(e=>`<option value="${e.id}">Nach Leg ${String(e.afterLeg).padStart(3,'0')} · ${esc(e.displayName||e.countryName)} · ${e.anchor}</option>`).join('');
 $('#xSelect').value=xSelected;
 $('#exceptions').innerHTML=X.excursions.map(e=>{const p=XA[e.target];return `<article class="exception" id="excursion-${e.id}"><div class="kicker">KAPITEL ${e.chapter} · NACH LEG ${String(e.afterLeg).padStart(3,'0')}</div><div class="tags"><span class="tag base">${esc(e.aircraft)}</span>${e.categoryVisit===false?'<span class="tag owned">Eigene Szenerie · Highlight-Ausflug</span>':''}${e.historical?'<span class="tag warn">Geschlossen · fiktiver Besuch</span>':e.conditional?'<span class="tag warn">Volanta-Nachweis offen</span>':''}</div><h3>${esc(e.displayName||e.countryName)}</h3><p class="side-trip mono">${e.route.map(esc).join(' → ')}</p><p><strong>${esc(e.title)}</strong></p><p>${esc(e.briefing)}</p>${e.experience?`<p><strong>Anflug erleben:</strong> ${esc(e.experience)}</p><p class="small">${esc(e.timing)}</p>`:""}<div class="xlegs">${e.legs.map(l=>`<label><input type="checkbox" data-xdone="${l.id}" ${state.xDone.has(l.id)?'checked':''}><span class="mono">${l.from} → ${l.to}</span><span class="mono ${l.over2h?'time-long':''}">${hm(l.airMin)} h · ${l.nm} NM${l.over2h?' *':''}</span></label>`).join('')}</div><p class="small">${p.type==='heliport'?'Heliport':`Piste im Datensatz: ${p.runway?fmt(p.runway)+' m':'unbekannt'} · Oberfläche ${esc(p.surface||'prüfen')}`} · ${p.lat.toFixed(5)}, ${p.lon.toFixed(5)}</p><p class="fuel-note"><strong>Treibstoff & Durchführung</strong><br>${esc(e.fuelNote)}</p><p class="small xverify">${esc(e.verification)}</p><p class="small"><strong>Warum dieses Fluggerät?</strong> ${esc(e.aircraftReason)}</p>${sceneryCard(e.target)}<div class="x-scenery-links">${[...new Set(e.route)].map(code=>`<button class="scenery-link" data-scenery="${code}">${code} · Szenerie →</button>`).join('')}</div><details><summary>Weitere Hinweise zum Landeplatz</summary><p>${esc(e.scenery)}</p><p>${esc(p.name)}</p><p><a href="${p.url}" target="_blank" rel="noopener noreferrer">Landeplatz im Datensatz ↗</a></p>${e.country==='TF'?'<p><a href="https://taaf.fr/collectivites/presentation-des-territoires/les-iles-eparses/" target="_blank" rel="noopener noreferrer">TAAF: Inseln und Zugehörigkeit ↗</a></p>':''}</details>${e.sources?.length?`<div class="source-links">${e.sources.map(([title,url])=>`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(title)} ↗</a>`).join("")}</div>`:""}<div class="card-footer"><button data-xmap="${e.id}">Ausflug auf der Karte →</button><button data-jump="${e.anchor}">A320 bei ${e.anchor} →</button></div></article>`}).join('');
 $('#xTotals').textContent=`${D.legs.length} A320-Legs + ${XL.length} Ausflugs-Legs = ${D.legs.length+XL.length} durchgehend verbundene Legs. Ausflüge zusammen ≈ ${hm(XL.reduce((n,l)=>n+l.airMin,0))} h; ${XL.filter(l=>l.over2h).length} davon über zwei Stunden. * Längere Etappen in Gold.`;
 $('#xFormula').textContent=X.formula;renderFleet();renderCountryRows();renderXProgress();
}
function renderCountryRows(){const q=normalize($('#countrySearch').value),filter=$('#countryFilter').value;$('#countryRows').innerHTML=D.countries.filter(c=>{const e=X.excursions.find(e=>e.country===c.code);return (!q||normalize(c.name+' '+c.code+' '+c.airports.join(' ')+' '+(e?.route.join(' ')||'')).includes(q))&&(filter==='all'||c.status===filter)}).sort((a,b)=>a.name.localeCompare(b.name)).map(c=>{const e=X.excursions.find(e=>e.country===c.code);return `<tr><td class="mono">${c.code}</td><td>${esc(c.name)}</td><td><span class="tag ${c.status==='main'?'owned':e&&!e.conditional?'base':'warn'}">${c.status==='main'?'A320 geplant':c.status==='special'?'Simulator-Sonderbetrieb':e.historical?'Historischer Simulator-Ausflug':e.conditional?'Zielvorschlag · Nachweis offen':'Ausflug geplant'}</span></td><td>${c.airports.length?c.airports.map(code=>`<button data-jump="${code}" style="font-size:12px;padding:2px 6px;margin:2px">${code}</button>`).join(' '):`<button data-xmap="${e.id}">${esc(e.target)} · ${esc(e.aircraft)} →</button>`}</td></tr>`}).join('')||'<tr><td colspan="4" class="empty">Keine passende Kategorie.</td></tr>'}
function renderXMap(){if(!$('#coverageView').classList.contains('active'))return;const e=X.excursions.find(x=>x.id===xSelected),host=$('#xMapHost'),w=host.clientWidth,h=370;if(!w)return;const codes=[...new Set(e.route)],coords=codes.map(c=>point(XA[c]));const projection=d3.geoMercator().fitExtent([[55,60],[w-95,h-70]],{type:'MultiPoint',coordinates:coords});const path=d3.geoPath(projection),svg=d3.select('#xMap').attr('viewBox',`0 0 ${w} ${h}`);svg.selectAll('*').remove();svg.append('title').text(`${e.countryName}: ${e.route.join(' nach ')}`);svg.append('g').selectAll('path').data(world.features).join('path').attr('class','land').attr('d',path);svg.append('g').selectAll('path').data(e.legs).join('path').attr('d',l=>path({type:'LineString',coordinates:[point(XA[l.from]),point(XA[l.to])]})).attr('fill','none').attr('stroke','#c5acf6').attr('stroke-width',2.5).attr('stroke-dasharray','6 5');const pins=svg.append('g').selectAll('g').data(codes).join('g').attr('transform',c=>`translate(${projection(point(XA[c]))})`);pins.append('circle').attr('r',6).attr('fill',c=>c===e.anchor?'#75e1c2':'#c5acf6').attr('stroke','#09151d').attr('stroke-width',2);pins.append('title').text(c=>`${c} · ${XA[c].name}`);pins.append('text').attr('class','airport-label').attr('x',10).attr('y',-10).text(c=>c);$('#xMapCaption').innerHTML=`<strong>${esc(e.countryName)}</strong> · ${esc(e.title)}<br><span class="mono">${e.route.join(' → ')}</span> · ${esc(e.aircraft)}<br><span class="small muted">Kartenlinie = Verbindung der Landestellen. Hin- und Rückweg liegen übereinander; keine Navigations- oder Geländefreigabe.</span>`;$('#xSelect').value=xSelected}
function openExcursion(id){xSelected=id;showView('coverageView');renderXMap();$('#xMapHost').scrollIntoView({block:'center',behavior:'smooth'})}
$('#xSelect').onchange=e=>{xSelected=e.target.value;renderXMap()};
document.addEventListener('click',e=>{const b=e.target.closest('[data-xmap]');if(b)openExcursion(b.dataset.xmap)});
$('#exceptions').addEventListener('change',e=>{const id=e.target.dataset.xdone;if(!id)return;if(e.target.checked)state.xDone.add(id);else state.xDone.delete(id);saveAll()});
new ResizeObserver(()=>{if($('#coverageView').classList.contains('active'))renderXMap()}).observe($('#xMapHost'));
function allJourney(){
 const rows=[];
 for(const l of D.legs){
  const a=A[l.to];
  rows.push({...l,kind:'A320',profile:'A320',aircraft:D.meta.aircraft,country:a.countryName,title:a.name,note:[a.highlight?.join(': '),a.note,B?.[l.to]?.experience].filter(Boolean).join(' '),sources:[a.runwaySource||a.url].filter(Boolean).join(' | '),conditional:false});
  for(const e of X.excursions.filter(e=>e.afterLeg===l.id))for(const x of e.legs)rows.push({...x,kind:'Ausflug',profile:e.profile,aircraft:e.aircraft,excursion:e.id,afterLeg:e.afterLeg,country:XA[x.to].country===e.country?e.countryName:D.countries.find(c=>c.code===XA[x.to].country)?.name||XA[x.to].country,title:XA[x.to].name,note:[e.briefing,e.experience,e.fuelNote].filter(Boolean).join(' '),sources:[XA[x.to].url,...(e.sources||[]).map(s=>s[1])].join(' | '),conditional:e.conditional});
 }
 return rows.map((l,i)=>({...l,sequence:i+1}));
}
function isJourneyDone(l){return l.kind==='A320'?state.done.has(l.id):state.xDone.has(l.id)}
function renderJourney(){
 const all=allJourney(),q=normalize($('#journeySearch').value),fleet=$('#journeyFleet').value||'all',status=$('#journeyStatus').value||'all';
 const rows=all.filter(l=>(fleet==='all'||fleet===l.profile)&&(!q||normalize([l.from,l.to,l.title,l.country,l.note].join(' ')).includes(q))&&(status==='all'||status==='long'&&l.over2h||status==='done'&&isJourneyDone(l)||status==='open'&&!isJourneyDone(l)));
 $('#journeyRows').innerHTML=rows.map(l=>`<tr class="${l.kind==='Ausflug'?'side':''}"><td><input type="checkbox" class="table-check" data-journeyid="${l.id}" data-kind="${l.kind}" aria-label="Flug ${l.sequence} als geflogen markieren" ${isJourneyDone(l)?'checked':''}></td><td class="mono">${String(l.sequence).padStart(3,'0')}<div class="airport-name">${l.kind==='A320'?'A320 '+String(l.id).padStart(3,'0'):'Ausflug'}</div></td><td class="mono airport-pair">${esc(l.from)} → ${esc(l.to)}</td><td><span class="tag ${l.profile==='A320'?'owned':l.profile==='H160'?'base':'warn'}">${l.profile==='A320'?'Fenix A320':l.profile==='H160'?'H160':'Twin Otter'}</span></td><td>${esc(l.title)}<div class="airport-name">${esc(l.country)}</div></td><td class="mono ${l.over2h?'time-long':''}">${hm(l.airMin)} h<div class="airport-name">${l.nm} NM</div></td><td>${sceneryButton(l.to)}</td><td><button ${l.kind==='A320'?`data-mainleg="${l.id}"`:`data-xmap="${l.excursion}"`}>Briefing →</button><div class="airport-name"><button data-debrief="${esc(l.id)}">Debriefing →</button></div></td></tr>`).join('')||'<tr><td colspan="8" class="empty">Keine passenden Legs.</td></tr>';
 $('#journeyTotals').textContent=`${all.length} verbundene Legs · ${state.done.size+state.xDone.size} lokal geflogen · EDLV → EDLV · ≈ ${hm(all.reduce((n,l)=>n+l.airMin,0))} h Flugzeit`;
 $('#journeyCount').textContent=`${rows.length} von ${all.length} Legs angezeigt. Filter behalten die ursprüngliche Flugreihenfolge bei.`;
 $('#retiredDetails').hidden=state.retiredXDone.size===0;
 $('#retiredRows').innerHTML=(X.retiredLegs||[]).filter(l=>state.retiredXDone.has(l.id)).map(l=>`<p>✓ ${esc(l.from)} → ${esc(l.to)} · ${esc(l.country)} · frühere Direktverbindung</p>`).join('');
}
for(const id of ['#journeySearch','#journeyFleet','#journeyStatus'])$(id).addEventListener(id==='#journeySearch'?'input':'change',renderJourney);
$('#journeyRows').addEventListener('change',e=>{const id=e.target.dataset.journeyid;if(!id)return;const main=e.target.dataset.kind==='A320',set=main?state.done:state.xDone,key=main?Number(id):id;if(e.target.checked)set.add(key);else set.delete(key);saveAll();renderRows();renderDetail()});
document.addEventListener('click',e=>{const b=e.target.closest('[data-mainleg]');if(!b)return;const l=D.legs[Number(b.dataset.mainleg)-1];showView('tourView');setChapter(l.chapter,false);selectLeg(l.id,true)});
function renderExpeditions(){
 $('#expeditionGrid').innerHTML=X.excursions.filter(e=>e.highlightCard).map(e=>`<article class="highlight-card ${e.country==='AQ'?'featured':''}"><div class="kicker">${e.profile==='DHC6'?'TWIN OTTER':'H160'} · NACH A320-LEG ${String(e.afterLeg).padStart(3,'0')}</div><div class="bigcode">${e.target}</div><h3>${esc(e.title)}</h3><p>${esc(e.experience)}</p><h4>So lohnt sich der Anflug</h4><p>${esc(e.timing)}</p><h4>Die feste Route</h4><p class="mono">${e.route.join(' → ')}</p><p>${e.legs.length} Legs · zusammen ≈ ${hm(e.legs.reduce((n,l)=>n+l.airMin,0))} h</p>${e.country==='AQ'||e.country==='TV'?`<p class="fuel-note">${e.country==='AQ'?'Rund 4:21 h je Richtung. Vorbereitete Betankung in SCRM und individuelle Reichweitenprüfung gehören zum Plan.':'Tankstopps auf Yasawa, Rotuma und Funafuti als vorbereitete Simulatorversorgung. Vier H160-Legs mit etwa 2:15 bzw. 2:21 Stunden.'}</p>`:''}<div class="card-footer"><span class="tag warn">${esc(e.countryName)}</span>${sceneryButton(e.target)}<button data-xmap="${e.id}">Ausflug & Briefing →</button></div></article>`).join('');
}
$('#fullCsvExport').onclick=()=>{
 const rows=[['Reihenfolge','Leg_ID','Art','Von','Nach','Flugzeug','Ziel','Kategorie_am_Ziel','NM','Flugzeit_Min','Blockzeit_Min_A320','Lokal_geflogen','Volanta_Wertung','Hinweise_Anflug_Treibstoff','Quellen','Szenerie_Empfehlung','Empfohlenes_Produkt_Basis','Szenerie_Begruendung','Szenerie_Quellen','Debriefing_Status','Tatsaechliche_Szenerie_Abflug','Tatsaechliche_Szenerie_Ankunft','Berichtetes_Flugdatum'],...allJourney().map(l=>[l.sequence,l.id,l.kind,l.from,l.to,l.aircraft,l.title,l.country,l.nm,l.airMin,l.blockMin||'',isJourneyDone(l)?'Ja':'Nein','Nach Flug kontrollieren',l.note,l.sources,sceneryLabel(l.to),SC.airports[l.to].recommendation,SC.airports[l.to].reason,SC.airports[l.to].links.map(s=>s[1]).join(' | '),debriefStatus(l),debriefSceneryText(debriefRecord(l)?.actualScenery?.departure),debriefSceneryText(debriefRecord(l)?.actualScenery?.arrival),debriefRecord(l)?.flightDate||''])];
 download('Volanta-Worldtour-245-Komplette-Reihenfolge.csv','\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\r\n'),'text/csv;charset=utf-8');toast('Alle Fluggeräte in fester Flugreihenfolge exportiert');
};
$('#journeyCsv').onclick=()=>$('#fullCsvExport').onclick();
$('#backupExport').onclick=()=>download('Worldtour-EDLV-Fortschritt.json',JSON.stringify({tour:'EDLV-2026-09-v1',routeVersion:2,total:D.legs.length,done:[...state.done],xDone:[...state.xDone],retiredXDone:[...state.retiredXDone],savedAt:new Date().toISOString()},null,2),'application/json');
$('#backupFile').onchange=async e=>{
 const f=e.target.files[0];if(!f)return;
 try{
  const s=JSON.parse(await f.text());
  if(s.tour!=='EDLV-2026-09-v1'||s.total!==D.legs.length||!Array.isArray(s.done)||!s.done.every(id=>Number.isInteger(id)&&id>0&&id<=D.legs.length)||(s.xDone!==undefined&&(!Array.isArray(s.xDone)||!s.xDone.every(id=>xIDs.has(id)||retiredIDs.has(id))))||(s.retiredXDone!==undefined&&(!Array.isArray(s.retiredXDone)||!s.retiredXDone.every(id=>retiredIDs.has(id)))))throw Error();
  state.done=new Set(s.done);restoreXProgress(s);saveAll();renderRows();renderDetail();renderCoverage();toast(state.retiredXDone.size?'Fortschritt geladen; frühere Direkt-Legs im Archiv erhalten':'Hauptroute und Ausflugsfortschritt geladen');
 }catch(err){toast('Diese Sicherung passt nicht zu dieser Tour.')}
 e.target.value='';
};

$('#xBriefing').onclick=()=>document.getElementById('excursion-'+xSelected).scrollIntoView({block:'start',behavior:'smooth'});
function renderInventory(){
 $('#inventory').innerHTML=D.inventory.map(i=>{const side=(X.bonusOwnedAirports||[]).includes(i.icao),used=i.inRoute||side;return `<div title="${esc(i.inRoute?'In der A320-Hauptroute':side?'H160-Ausflug':i.reason)}"><span class="mono" style="color:${used?'var(--teal)':'var(--gold)'}">${used?'✓':'◇'} ${i.icao}</span><small>${esc(i.manufacturer)}</small>${side?'<small>Im H160-Ausflug</small>':i.inRoute?'':`<small style="margin-top:5px">${esc(i.reason)}</small>`}</div>`}).join('');
}
$('#sources').innerHTML+=`<a href="${X.h160Source}" target="_blank" rel="noopener noreferrer">Airbus: H160 technische Daten ↗</a><a href="${X.h160ImplementationSource}" target="_blank" rel="noopener noreferrer">HPG: H160 im Simulator ↗</a><a href="https://www.flightsimulator.com/aircraft-manuals/" target="_blank" rel="noopener noreferrer">MSFS: Flugzeughandbücher ↗</a>`;
