from pathlib import Path
p=Path('work/route_source.py');s=p.read_text(encoding='utf8')
s=s.replace('FWKI FLKK FVFA FBKE FYWH FYLZ FACT FALE FDSK FXMM FAOR FQMA FQBR FVHA FLKK FZLub FNUB FNLU','FWKI FQBR FQMA FDSK FALE FXMM FAOR FACT FYLZ FYWH FBKE FVFA FVHA FLKK FZLub FNUB FNLU')
s=s.replace('FHAW FPST FOOL FGSL FKKD FEFF FTTJ DRRN DFFD GABS GUCY GFLL GLRB DIAP DGAA DXXX DBBB DNMM FZAA FCBB FKKD DNMM DGAA GLRB GUCY GGOV GBYD GOBD GVAC','FHAW FPST FOOL FZAA FCBB FGSL FKKD FEFF FTTJ DRRN DNMM DBBB DXXX DGAA DFFD GABS DIAP GLRB GFLL GUCY GGOV GBYD GOBD GVAC')
s=s.replace('WIMM VOBL VOMM','WIMM VOPB VOMM VOBL VOMM')
s=s.replace('CYVP CYOW','CYVP CYWK CYOW')
s=s.replace('WBKK WMKK WSSS WIII YPXM YPCC WIMM','WBKK WMKK WSSS WIII YPXM YPCC WICT WIMM')
s=s.replace('UAAA UACC UAKK ZMCK','UAAA UASK ZMCK')
p.write_text(s,encoding='utf8')
