"""Curated, continuous airport sequence. Data enrichment in build_data.py."""
CHAPTERS = [
('01','Europa & Nordatlantik','Von Weeze über die Inseln des Nordatlantiks nach Kanada.', '''EDLV EHAM EBBR ELLX EGLL EGJJ EICK EGNS EGGP EGPB EKVG BIAR BIKF BGGH CYFB CYVP CYWK CYOW CYQM LFVP CYYT'''),
('02','Atlantik & Karibik','Bermuda, die Kleinen Antillen und die ABC-Inseln.', '''KBOS KJFK KORF TXKF TJSJ TIST TNCM TKPK TAPA TFFR TFFF TLPL TVSA TBPB TGPY TTCP TNCB TNCC TNCA SVMI'''),
('03','Die Guyanas & Brasilien','Atlantikküste, Amazonas und ein Bogen zu den Iguazúfällen.', '''SYCJ SMJP SOCA SBMQ SBSN SBEG SBPV SBBR SBCF SBGL SBFI SGAS SUMU SAEZ'''),
('04','Patagonien & Anden','Feuerland, Falklandinseln, die Anden und die Pazifikküste.', '''SAZB SAVT SAWG EGYP SAWH SCCI SCBA SCTE SCIE SCEL SCAT SCFA SLLP SLVR SPZO SPJC SPHI SEGU SEGS SEGU SKCL SKBO SKCG MPTO'''),
('05','Mittelamerika & Große Antillen','Die Landbrücke und ein zusammenhängender Inselbogen.', '''MROC MNMG MHTG MSLP MGGT MZBZ MMUN MWCR MKJS MTPP MDPP MBPV MYEH MYNN MUHA MMMD MMVR MMMX'''),
('06','Nordamerika & Hawaii','Wüsten, Rocky Mountains und die längere Pazifikquerung.', '''MMGL MMSD MMHO KPHX KLAS KDEN KSLC KSFO KLAX PHNL PHKO PHNL'''),
('07','Mikronesien','Über Midway und Wake zu den Inselketten des Westpazifiks.', '''PMDY PWAK PKMJ PTPN PTKK PGUM PGSN PTRO RPMD WAMM WABB AYPY'''),
('08','Südpazifik','Salomonen, Nauru, Kiribati und die Inseln Polynesiens.', '''AGGH ANYN NGTA NFFN NLWW NSFA NSTU NIUE NCRG NTAA NCRG NFTF NFFN NVVV NWWW YSNF NZAA'''),
('09','Neuseeland & Australien','Vulkane, Südalpen, Sydney und das australische Outback.', '''NZRO NZWN NZQN NZCH NZQN YMHB YMML YSSY YBCG YBBN YBRK YBCS YBTL YBAS YAYE YPKG YPPH YPLM YBRM YPDN'''),
('10','Südostasien','Timor, Indonesien, Singapur und die Andamanensee.', '''WPDL WADD WAHQ WIII WIOO WBSB WBKK WMKK WSSS WIII YPXM YPCC WIEE WIMM VTSP VTBS VDSV VVTS VVCR VVDN VVNB VLLB VYYY VGHS'''),
('11','Himalaya & Zentralasien','Paro, Nepal, die Seidenstraße und die Steppe.', '''VQPR VNKT VIBN VIDP VIAR OPIS OAKB UTDD UCFM UAAA UASK ZMCK UIII UIUU ZBHH ZBAA ZYTL ZKPY RKSI RKPC RJFR RJOO RJTT RJCK'''),
('12','Ostasien & Indischer Ozean','Japan, Taiwan, Hongkong und ein südlicher Bogen nach Indien.', '''RJTT RJFU RORS RCTP VHHH VMMC RPLL RPVP WBKK WBSB WIOO WIII WIPP WIMM VOPB VOMM VOBL VOMM VCBI VRMM VOCI VOGO VABB VAAH OPKC OOMS'''),
('13','Arabien & Naher Osten','Wüstenküsten, Golfstaaten, Levante und Kaukasus.', '''OMDB OBBI OTHH OKBK OERK OEMA OJAI LLBG OLBA OSDI ORBI OIIE UTAK UTAA UTTT UTAA UBBB UDYZ UGTB LTCG LTAI LCLK HECA'''),
('14','Ostafrika & Inseln','Rotes Meer, ostafrikanischer Graben und der Indische Ozean.', '''HESN HSSS HHAS HAAB HDAM HCMH OYSQ OOSA OYSQ HCMH HKJK HUEN HSSJ HUEN HRYR HBBA HTKJ HTZA HKMO FSIA FJDG FIMP FMEE FIMP FMMI FMNN FMCZ FMCH FQPB'''),
('15','Südliches Afrika','Seen, Sambesi, Namib und Kap der Guten Hoffnung.', '''FWKI FQBR FQMA FDSK FALE FXMM FAOR FACT FYLZ FYWH FBKE FVFA FVHA FLKK FZLub FNUB FNLU'''),
('16','Zentral- & Westafrika','Ein Atlantikabstecher und die Küsten Westafrikas.', '''FHAW FPST FOOL FZAA FCBB FGSL FKKD FEFF FTTJ DRRN DNMM DBBB DXXX DGAA DFFD GABS DIAP GLRB GFLL GUCY GGOV GBYD GOBD GVAC'''),
('17','Sahara & Mittelmeer','Kapverden, Westsahara, Madeira und der westliche Mittelmeerraum.', '''GQNO GMMH GCLP LPMA LPPT LPFR LXGB GEML GMMN DAAG HLLT DTTJ LMML LICJ LIRF LFMN LEPA LEBL LSGG LSZH LOWI LOWS LOWG'''),
('18','Balkan & Osteuropa','Adriaküste, Balkan und Karpaten.', '''LJLJ LDRI LDDU LYTV LATI BKPR LWSK LGKR LGAV LGSM LGAV LBSF LQSA LYBE LHBP LZTT LRCL LROP LUKK UKLL UMMS EYVI EVRA EETN'''),
('19','Nordlicht & Heimkehr','Åland, Lappland, Svalbard und zurück nach Weeze.', '''EFMA ESSA EFVA EFIV ESNQ ENTC ENSB ENTC ENVA ENGM EKCH EKRN EPWA EPKK LKKV EDDB EDDP EDDN EDDM EDDF EDDK EDLV''')
]

# Explicit replacements for obsolete / ambiguous identifiers are resolved before enrichment.
ALIASES={'FZLub':'FZQA','VIBN':'VEBN','OKBK':'OKKK','HSSS':'HSSK','HSSJ':'HJJJ','HLLT':'HLLM','EGPB':'EGPE'}

# Places deliberately outside the standard A320 itinerary. No nearby stop counts as a visit.
EXCEPTIONS = {
 'AD':('Kein Flugplatz','Andorra hat keinen Flughafen für Flächenflugzeuge. LESU liegt in Spanien.','LEBL','Helikopterausflug nach La Massana prüfen; Volantas Wertung eines Heliports separat testen.'),
 'AI':('Regionalflugzeug','Anguilla: etwa 1.665 × 30 m. Nicht als regulären Fenix-A320-Stopp eingeplant.','TNCM','TNCM → TQPF → TNCM mit ATR oder geeignetem kleineren Flugzeug.'),
 'AQ':('Expedition','Antarktis: Eis-/Schotterpisten und Expeditionsbetrieb. Keine normale Fenix-A320-Etappe.','SAWH','DHC-6-Expedition über SCRM oder Marambio separat planen; keine A320-Freigabe.'),
 'BL':('Kleinflugzeug','Saint Barthélemy: TFFJ, etwa 646 m und steiler Hügelanflug.','TNCM','TNCM → TFFJ → TNCM mit DHC-6 oder Caravan.'),
 'DM':('Regionalflugzeug','Dominica: TDPD ist kurz und liegt in anspruchsvollem Gelände. Kein regulärer A320-Stopp angesetzt.','TFFR','TFFR → TDPD → TFFR mit ATR. Ein neuer internationaler Flughafen wird nicht als vorhanden angenommen.'),
 'GG':('Regionalflugzeug','Guernsey: EGJB mit etwa 1.583 m. Für diesen Plan außerhalb der normalen A320-Auswahl.','EGJJ','EGJJ → EGJB → EGJJ mit ATR.'),
 'LI':('Kein Flugplatz','Liechtenstein hat keinen geeigneten Flughafen. LSZR liegt in der Schweiz.','LSZH','Helikopter nach Balzers LSXB prüfen; kein Länderpunkt durch LSZR.'),
 'MC':('Helikopter','Monaco hat einen Heliport, keinen A320-Flughafen. LFMN liegt in Frankreich.','LFMN','Helikopter LFMN → LNMC → LFMN; Volanta-Heliportwertung prüfen.'),
 'MF':('Regionalflugzeug','Saint Martin ist die französische Inselhälfte. TFFG hat etwa 1.200 m; TNCM zählt Sint Maarten.','TNCM','TNCM → TFFG → TNCM mit geeignetem Regional- oder Kleinflugzeug.'),
 'MS':('Kleinflugzeug','Montserrat: TRPG mit etwa 596 m Piste.','TAPA','TAPA → TRPG → TAPA mit passendem Kleinflugzeug.'),
 'PS':('Nicht regulär erreichbar','Palästina hat keinen regulär nutzbaren A320-Flughafen. LLBG liegt in Israel.','LLBG','Nur separat mit passender historischer Szenerie / Heliport und bestätigter Volanta-Zuordnung prüfbar.'),
 'SM':('Kleinflugzeug','San Marino: Torraccia LIKD ist ein kurzer Grasflugplatz. LIPR liegt in Italien.','LIRF','Kleinflugzeugausflug nach LIKD separat planen.'),
 'TF':('Expedition','Französische Südgebiete: kein normaler A320-Airport in der Kategorie.','FMEE','Tromelin oder eine andere tatsächlich zu TF gehörende Landestelle nur mit passendem Flugzeug und überprüfter Zuordnung.'),
 'TV':('Regionalflugzeug','Tuvalu: Funafuti NGFU mit etwa 1.536 × 24 m. Kein normaler A320-Stopp.','NFFN','NFFN → NGFU → NFFN mit ATR; längere Turboprop-Etappen einplanen.'),
 'VA':('Helikopter','Vatikan: kein Flughafen für Flächenflugzeuge; LIRF liegt in Italien.','LIRF','Helikopterlandung im Vatikan nur bei verfügbarer Szenerie und bestätigter Volanta-Wertung.'),
 'VG':('Regionalflugzeug','British Virgin Islands: TUPJ etwa 1.415 × 27 m.','TIST','TIST → TUPJ → TIST mit ATR oder kleinerem Flugzeug.')
}

SPECIAL = {
 'PMDY':'Midway: abgelegener Ausweich-/Sonderflugplatz. Diese Etappe ist als Simulator-Sonderbetrieb geplant; kein reguläres Airline-Ziel.',
 'PWAK':'Wake Island: militärischer Sonderflugplatz. Nur als ausdrücklich fiktiver Simulator-Stopp eingeplant.',
 'FHAW':'Ascension: RAF-Flugplatz mit langer Piste, als fiktiver Simulator-Sonderbetrieb geplant. Am 21.09.2026 in Volantas Flughafenansicht direkt geprüft: FHAW gehört zur Kategorie Saint Helena (SH). Kein Besuch der Insel St Helena selbst; Länderpunkt nach dem Flug kontrollieren.',
 'FJDG':'Diego Garcia: Militärbasis im Britischen Territorium im Indischen Ozean. Fiktiver Simulator-Stopp, kein regulärer Passagierverkehr.',
 'EGYP':'Mount Pleasant: zivil-militärischer Flughafen; Wind und Abgelegenheit berücksichtigen.',
 'VQPR':'Paro: sehr anspruchsvoller Sichtanflug zwischen Bergen. Tagsüber, gute Sicht, geringe Masse und eigenes Briefing. A320-Familie real eingesetzt; keine automatische Fenix-Verfahrensfreigabe.',
 'LOWI':'Innsbruck: Tal- und Terrainverfahren, Föhn, besondere Anflug- und Missed-Approach-Anforderungen. Nur nach Briefing.',
 'NZQN':'Queenstown: Bergterrain; RNP-AR-Verfahren nicht ohne Prüfung der Fenix-Fähigkeiten voraussetzen. Geeignetes veröffentlichtes Verfahren wählen.',
 'LPMA':'Madeira: Windscherung und Seitenwind sind entscheidend. Abflug- und Landewerte sowie Windsituation prüfen.',
 'LXGB':'Gibraltar: Fels, Turbulenz und besondere Anfluggeometrie. Aktuelle Simulator-Charts prüfen.',
 'LGSM':'Samos: anspruchsvolle Terrain-/Windlage, sorgfältiges Anflugbriefing nötig.',
 'SLLP':'La Paz: große Platzhöhe. Masse und Temperatur wirken stark auf Startleistung; kurze Folgeetappe nach Santa Cruz.',
 'SPZO':'Cusco: großer Höhenunterschied und enges Tal. Leistungs- und Anflugplanung ist Teil dieser Etappe.',
 'MHTG':'Tegucigalpa/Toncontín: anspruchsvoller Anflug. A320-Familie historisch eingesetzt; heutiger ziviler Verkehr teilweise nach Palmerola verlagert.',
 'BGGH':'Nuuk: Datensatz nutzt die neue 2.200-m-Bahn. Vorher prüfen, ob deine M’M-Szenerie diese Bahn enthält; die alte 950-m-Bahn ist ungeeignet.',
 'EFMA':'Mariehamn liegt geografisch auf Åland. Für die Abdeckung AX statt der OurAirports-Länderzuordnung FI verwendet.',
 'ENSB':'Longyearbyen zählt hier zu Svalbard (SJ), nicht zur separaten Volanta-Kategorie Norwegen.',
 'TNCM':'Princess Juliana: Maho Beach liegt unmittelbar vor der Bahn. Der Flughafen zählt Sint Maarten; Saint Martin ist eine separate Kategorie.',
 'TNCB':'Bonaire deckt die gemeinsame Kategorie „Bonaire, Sint Eustatius and Saba“ ab. Ein A320-Stopp auf Saba ist dafür nicht nötig.',
 'LKKV':'Karlovy Vary: relativ kurze Bahn und erhöhte Platzlage; Tagesleistung im Fenix-EFB berechnen.',
 'EGJJ':'Jersey: kurze Bahn. Nutzlast konservativ wählen und Start-/Landestrecke mit aktuellem Wetter berechnen.',
 'EGNS':'Isle of Man: relativ kurze Bahn. Fenix-EFB-Leistungsrechnung vor dem Flug.',
 'NGTA':'Tarawa: relativ kurze Inselbahn. Wind, Nutzlast und verfügbarer Ausweichplatz beeinflussen die Planung.',
 'ANYN':'Nauru: kurze Inselbahn mit wenigen Alternates; Nutzlast und Kraftstoff sorgfältig abstimmen.',
 'YSNF':'Norfolk Island: abgelegen und wetterabhängig. Landestrecken und Alternate-Kraftstoff prüfen.',
 'MYEH':'North Eleuthera: etwa 1.835 × 30 m. Als anspruchsvoller Simulator-Stopp enthalten; Breite und Performance besonders prüfen.',
 'GEML':'Melilla: sehr kurze Bahn. Wird bei der Datenprüfung aus der A320-Hauptroute entfernt; Spanien ist bereits abgedeckt.'
}

HIGHLIGHTS = {
 'EKVG':('Färöer','Wolkenlücken zwischen steilen Inselhängen und ein kompakter Anflug auf Vágar.'),
 'BIAR':('Eyjafjörður','Ein langer Fjord führt nach Akureyri; ideal bei Tageslicht.'),
 'BGGH':('Grönland','Fjorde, Inseln und felsige Küsten rund um Nuuk.'),
 'LFVP':('Frankreich vor Kanada','Saint-Pierre ist ein eigenständiges Volanta-Territorium, direkt vor Neufundland.'),
 'TXKF':('Bermuda','Türkise Lagunen und eine Piste mitten in einer schmalen Inselkette.'),
 'TNCM':('Maho Beach','Einer der markantesten Airliner-Anflüge der Tour.'),
 'TLPL':('St Lucia','Die Pitons liegen nordwestlich des Airports; eine Sichtung hängt von der Route ab.'),
 'SBSN':('Amazonas','Breite Flussarme am Zusammenfluss von Tapajós und Amazonas.'),
 'SBGL':('Rio de Janeiro','Guanabara-Bucht und Stadtberge. Santos Dumont als Blickfang, nicht als reguläres Fenix-Ziel.'),
 'SBFI':('Iguazú','Wasserfälle im Dreiländereck; Sichtflug-Abstecher separat vom IFR-Anflug planen.'),
 'SAWH':('Feuerland','Beagle-Kanal und Bergkulisse am südlichen Ende Südamerikas.'),
 'SCBA':('Patagonische Fjorde','Zerklüftete Küsten und Andenlandschaft auf dem Weg nach Norden.'),
 'SCFA':('Atacama','Pazifik trifft Wüste; die Küstenlinie bietet starke Kontraste.'),
 'SLLP':('Altiplano','Hochplateau und Andenkette; die Platzhöhe macht das Leg fliegerisch besonders.'),
 'SPZO':('Cusco','Ein Gebirgstal als Anflugkulisse. Machu Picchu ist kein direkter Airport-POI und kein zugesagter Überflug.'),
 'SEGS':('Galápagos','Vulkaninseln im Pazifik; bewusst ein längerer Abstecher innerhalb der Ecuador-Kategorie.'),
 'MHTG':('Toncontín','Markanter Stadt- und Tal-Anflug; ein bewusst anspruchsvolles Highlight.'),
 'KLAS':('Mojave','Wüste, Las Vegas Strip und Lake Mead je nach Anflugrichtung.'),
 'KPHX':('Arizona','Von hier aus ist Sedona KSEZ als separates Kleinflugzeug-Highlight erreichbar.'),
 'KDEN':('Rocky Mountains','Ein geografisch sinnvoller Bogen nutzt deine Flightbeam-Szenerie.'),
 'KSFO':('San Francisco Bay','Küstenanflug, Bucht und Golden Gate je nach Wetter und Verfahren.'),
 'PHNL':('Oʻahu','Diamond Head, Honolulu und Pearl Harbor als regionale Blickfänge.'),
 'PHKO':('Lava & Ozean','Kona liegt zwischen dunklen Lavafeldern und dem Pazifik; handgefertigt in WU XIII.'),
 'PTPN':('Pohnpei','Vulkaninsel, Riffkante und handgefertigter WU-XIII-Airport.'),
 'AGGH':('Salomonen','Guadalcanal mit tropischen Bergen und Küstenlandschaft.'),
 'NTAA':('Tahiti','Vulkaninsel und Lagune. Bora Bora NTTB ist ein schöner separater Regionalflug, kein A320-Stopp.'),
 'NCRG':('Rarotonga','Ringförmige Küste, Lagune und steile grüne Inselberge.'),
 'NZRO':('Rotorua','Seen und Vulkanlandschaft; handgefertigter WU-XII-Airport.'),
 'NZQN':('Südalpen','Lake Wakatipu und ein alpiner Anflug. Deine Milford-Sound-Szenerie NZMF bleibt ein Kleinflugzeug-Ausflug.'),
 'YSSY':('Sydney Harbour','Küstenmetropole mit Harbour Bridge und Oper; deine FlyTampa-Szenerie.'),
 'YAYE':('Uluru','Der rote Fels liegt südöstlich des Airports. Eine Sichtung braucht passende Route und Sicht.'),
 'YBRM':('Kimberley','Rote Erde, türkisfarbenes Wasser und der handgefertigte Airport aus WU 21.'),
 'YPXM':('Christmas Island','Steile tropische Insel und abgelegene Piste im Indischen Ozean.'),
 'YPCC':('Cocos Islands','Eine lange Piste auf einem Korallenatoll.'),
 'VQPR':('Paro','Der Himalaya-Höhepunkt der Tour, mit bewusst hohem Briefingbedarf.'),
 'VNKT':('Kathmandu','Talbecken mit Himalaya-Kulisse bei klarer Sicht.'),
 'RJFR':('Kitakyūshū','Künstliche Flughafeninsel, seit WU 20 handgefertigt.'),
 'RORS':('Shimojishima','Leuchtendes Riffwasser direkt am Bahnanfang.'),
 'VHHH':('Hongkong','Inselairport zwischen Bergen, Seewegen und dicht bebauter Stadtlandschaft.'),
 'VRMM':('Malediven','Eine Hauptpiste inmitten türkisfarbener Atolle.'),
 'OMDB':('Dubai','Wüstenskyline und deine iniBuilds-Szenerie.'),
 'OYSQ':('Socotra','Karge Gebirge und eine außergewöhnlich abgelegene Insel.'),
 'HTKJ':('Kilimanjaro','Bei klarer Sicht prägt der Vulkan die Region des Airports.'),
 'FSIA':('Seychellen','Granitberge, Strandküste und das Meer direkt neben der Piste.'),
 'FMEE':('Réunion','Vulkanisches Inselrelief. Piton de la Fournaise liegt weit vom regulären Anflug entfernt.'),
 'FVFA':('Victoriafälle','Sambesi und Wasserfallregion; die Fälle liegen nicht automatisch auf dem IFR-Track.'),
 'FYWH':('Namibisches Hochland','Trockenes Hochland, weite Sicht und eine Etappe Richtung Namibküste.'),
 'FACT':('Kapstadt','Tafelberg und Kaphalbinsel als markante Landschaft.'),
 'GMMH':('Dakhla','Schmale Halbinsel zwischen Atlantik und Lagune; separate Kategorie Westsahara.'),
 'LPMA':('Madeira','Felsige Insel, Flughafenplattform und oft anspruchsvoller Wind.'),
 'LXGB':('Gibraltar','Der Fels direkt neben einer ungewöhnlichen Landebahn.'),
 'LFMN':('Côte d’Azur','Meeresanflug mit Alpen im Hintergrund; handgefertigt in WU IV.'),
 'LOWI':('Inntal','Deine iniBuilds-Szenerie und eine der prägnantesten Alpenkulissen.'),
 'LYTV':('Bucht von Kotor','Ein bergiger Küstenanflug nach Tivat.'),
 'LGSM':('Samos','Deine Terrainy-Szenerie und ein kurvenreicher Inselanflug.'),
 'LZTT':('Hohe Tatra','Handgefertigter WU-XIV-Airport am Fuß der Berge.'),
 'ENSB':('Svalbard','Arktische Fjorde und kahle Berge weit jenseits des Polarkreises.'),
 'EDLV':('Weeze','Start und Ziel der gesamten Reise mit deiner SimPixel-Szenerie.')
}
