const SC=JSON.parse($('#sceneryData').textContent);
const sceneryModes={owned:['Vorhanden nutzen','owned'],included:['Enthalten nutzen','wu'],freeware:['Freeware empfohlen','freeware'],default:['Basis nutzen',''],verify:['Landestelle prüfen','warn'],buy:['Optionaler Highlight-Kauf','warn']};
function sceneryLabel(code){return sceneryModes[SC.airports[code].mode][0]}
function sceneryProduct(code){return SC.products[code]||SC.freeware[code]}
function freewareMetrics(p){return `${Number(p.rating).toFixed(1).replace('.',',')}/5 · ${p.reviews} Bewertungen · ca. ${fmt(p.downloads)} Downloads`}
function freewareDetails(p){return `<p><strong>${esc(freewareMetrics(p))}</strong></p><p><strong>2024:</strong> ${esc(p.compatibility)}</p><p><strong>Installation:</strong> ${esc(p.dependencies)}</p><p><strong>Beachten:</strong> ${esc(p.caveat)}</p><p class="small muted">Version ${esc(p.version)} · Update ${esc(p.updated)} · Recherche ${esc(SC.date)}</p>`}
function freewareReviewHtml(code){const rows=SC.freewareConsidered.filter(r=>r.codes.includes(code));return rows.length?`<details class="freeware-review"><summary>Weitere Freeware geprüft · vorerst zurückgestellt</summary>${rows.map(r=>`<p><strong>${esc(r.name)}</strong><br>${esc(r.metrics)}<br>${esc(r.reason)}<br><a href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">Prüfquelle ↗</a></p>`).join('')}</details>`:''}
function sceneryLinks(links){return `<div class="source-links">${links.map(([title,url])=>`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(title)} ↗</a>`).join('')}</div>`}
function sceneryComparison(code){
 const a=SC.airports[code].comparison;
 const free=a.freeware.map(f=>`<div class="comparison-product"><strong><a href="${esc(f.url)}" target="_blank" rel="noopener noreferrer">${esc(f.name)} ↗</a></strong><span class="comparison-stage ${f.stage==='Empfohlen'?'recommended':''}">${esc(f.stage)}</span>${f.metrics?`<div class="small">${esc(f.metrics)}</div>`:''}<p>${esc(f.verdict)}</p></div>`).join('');
 const paid=a.payware.map(p=>`<div class="comparison-product"><strong>${p.developer?esc(p.developer)+' · ':''}${esc(p.name)}</strong><span class="comparison-stage ${p.stage==='Optional empfohlen'?'recommended':''}">${esc(p.stage)}</span><div class="small">${p.platforms?.length?'Portal-/Produktangabe: '+esc(p.platforms.join(' / ')):''}${p.rating!==null&&p.rating!==undefined?` · ${esc(String(p.rating).replace('.',','))}/5 (${p.reviews})`:''}</div>${p.verdict?`<p>${esc(p.verdict)}</p>`:''}${p.compatibility?`<p class="small">${esc(p.compatibility)}</p>`:''}${p.links?sceneryLinks(p.links):`<a href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">Quelle ↗</a>`}</div>`).join('');
 return `<details class="comparison-details"><summary><span class="comparison-depth">${esc(a.depth)}</span> Freeware ↔ Payware · Vergleich öffnen</summary><div class="comparison-grid"><section><h4>Flightsim.to / Freeware</h4><p>${esc(a.freewareConclusion)}</p>${free||'<p class="small muted">Kein passender Einzelkandidat im erfassten Suchergebnis.</p>'}</section><section><h4>Kommerzielle Alternativen</h4><p>${esc(a.paywareConclusion)}</p>${paid||'<p class="small muted">Kein eindeutig zugeordnetes Produkt aus dem auslesbaren Preisportal erfasst. Weitere Webquellen siehe unten.</p>'}<p class="small muted">${a.fsacReadable?'FSAddonCompare-Seite ausgelesen. Katalogbewertungen sind keine gesonderten 2024-Testnoten.':'Die FSAddonCompare-ICAO-Suche lieferte für diesen Ort keine auswertbare Antwort. Einzelprodukte können über andere Quellen erfasst sein; die Angebotsliste kann unvollständig sein.'}</p>${sceneryLinks([['FSAddonCompare · Suche für '+code,a.fsacUrl]])}</section></div>${a.sources.length?`<div class="comparison-sources"><strong class="small">Weitere gefundene Quellen · keine automatische Kaufempfehlung</strong>${sceneryLinks(a.sources)}</div>`:''}<p class="small muted">Suchabgleich ${esc(a.date)} · „Produktseite geprüft“ umfasst Angaben und verfügbare Rückmeldungen, keinen eigenen Simulator-Test. Nicht vertiefte Treffer sind ausdrücklich gekennzeichnet.</p></details>`;
}
function sceneryButton(code){const g=SC.airports[code];return `<button class="scenery-link ${g.mode==='buy'?'buy':''}" data-scenery="${esc(code)}" aria-label="Szenerie-Empfehlung für ${esc(code)}">${esc(sceneryLabel(code))} ↗</button>`}
function sceneryCard(code){
 const g=SC.airports[code],p=sceneryProduct(code),f=SC.freeware[code];
 return `<div class="scenery-note ${g.mode==='buy'?'buy':f?'freeware':''}"><div class="kicker">Szenerie-Empfehlung · ${esc(code)}</div><strong>${esc(g.recommendation)}</strong>${f?`<p class="freeware-score">${esc(freewareMetrics(f))}</p>`:''}<p>${esc(g.reason)}</p>${p?`<p class="small">${esc(p.caveat)}</p>`:''}<button class="scenery-link" data-scenery="${esc(code)}">${f?'Download, 2024-Hinweise & Bibliotheken':p?'Belege, Alternative & Preisvergleich':'Hinweise & Quellen'} →</button></div>`;
}
function openScenery(code){
 $('#scenerySearch').value=code;$('#sceneryFilter').value='all';$('#sceneryDepth').value='all';renderScenery();showView('sceneryView');
 $('#sceneryCatalog').scrollIntoView({block:'start',behavior:'smooth'});
}
document.addEventListener('click',e=>{const b=e.target.closest('[data-scenery]');if(b){openScenery(b.dataset.scenery);return}const r=e.target.closest('[data-scenery-route]');if(r){const code=r.dataset.sceneryRoute;if(A[code])jumpToAirport(code);else{const x=X.excursions.find(e=>e.route.includes(code));if(x)openExcursion(x.id)}}});
function renderScenery(){
 const q=normalize($('#scenerySearch').value),mode=$('#sceneryFilter').value||'all',depth=$('#sceneryDepth').value||'all';
 const exact=SC.airports[q.toUpperCase()];
 const rows=SC.order.map(k=>SC.airports[k]).filter(g=>(mode==='all'||g.mode===mode)&&(depth==='all'||g.comparison.depth===depth)&&(!q||(exact?g.code===q.toUpperCase():normalize([g.code,g.name,g.country,g.recommendation,g.reason,...g.comparison.freeware.map(f=>f.name),...g.comparison.payware.map(p=>p.developer+' '+p.name)].join(' ')).includes(q))));
 $('#sceneryRows').innerHTML=rows.map(g=>{const p=SC.products[g.code],f=SC.freeware[g.code];return `<tr data-scenery-row="${g.code}"><td><strong class="mono">${g.code}</strong><div class="airport-name">${esc(g.name)}</div><div class="airport-name">${esc(g.country)}</div></td><td><span class="tag ${sceneryModes[g.mode][1]}">${esc(sceneryLabel(g.code))}</span><p class="scenery-choice">${esc(g.recommendation)}</p>${f?`<div class="airport-name">${esc(freewareMetrics(f))}</div>`:''}</td><td><p>${esc(g.reason)}</p><details ${p||f?'open':''}><summary>${esc(g.evidence)} · Details & Quellen</summary><p>${esc(g.note)}</p>${p?`<p>${esc(p.evidence)}</p><p>${esc(p.caveat)}</p><p>${esc(p.compatibility)}</p>`:f?freewareDetails(f):''}${sceneryLinks(g.links)}</details>${sceneryComparison(g.code)}</td><td><button data-scenery-route="${g.code}" aria-label="${g.code} in der Route öffnen">Route →</button></td></tr>`}).join('')||'<tr><td colspan="4" class="empty">Kein Airport passt zu Suche und Filter.</td></tr>';
 $('#sceneryCount').textContent=`${rows.length} von ${SC.order.length} Landestellen · Reihenfolge des ersten Tour-Besuchs · Recherchestand 21.09.2026`;
}
function renderSceneryOverview(){
 $('#sceneryMetrics').innerHTML=[['405','Airports & Landestellen'],[String(SC.counts.owned),'eigene Szenerien nutzen'],[String(SC.counts.included),'weitere enthaltene Airports'],[String(SC.counts.freeware),'Freeware-Empfehlungen'],[String(SC.counts.buy),'optionale Kauf-Ausnahmen']].map(([n,t])=>`<div><b class="mono">${n}</b><span>${t}</span></div>`).join('');
 const a=SC.auditSummary;
 $('#comparisonSummary').innerHTML=`<div><b>${a.screenedAirports} / 405</b><span>Landestellen im Suchabgleich</span></div><div><b>${a.productReviewedAirports}</b><span>Orte mit vertiefter Produktprüfung</span></div><div><b>${a.reviewedFreewareProducts}</b><span>Freeware-Projekte mit Entscheidung</span></div><div><b>${a.reviewedPaywareAirports}</b><span>Orte mit gezielter Kaufabwägung</span></div><p>${esc(a.method)} Von 405 FSAddonCompare-ICAO-Suchen lieferten ${a.fsacReadable} auswertbare Antworten, ${a.fsacUnavailable} blieben ohne auswertbares Ergebnis. Auch die auslesbaren Listen ersetzen keinen vollständigen Produktvergleich.</p>`;
 $('#freewarePolicy').textContent=SC.freewarePolicy;$('#freewareMetricsNote').textContent=SC.freewareMetricsNote;
 $('#freewareShortlist').innerHTML=Object.entries(SC.freeware).sort(([a],[b])=>SC.airports[a].order-SC.airports[b].order).map(([code,p])=>`<article class="freeware-card"><div class="kicker">Flightsim.to · Freeware</div><div class="freeware-card-top"><strong class="mono">${code}</strong><span class="freeware-score">${Number(p.rating).toFixed(1).replace('.',',')}<small> / 5</small></span></div><div class="freeware-proof">${p.reviews} Bewertungen · ca. ${fmt(p.downloads)} Downloads</div><h3>${esc(p.headline)}</h3><p class="scenery-product">${esc(p.developer)} · ${esc(p.name)}</p><p>${esc(p.reason)}</p><details><summary>2024-Ausgabe, Bibliotheken & Einschränkungen</summary>${freewareDetails(p)}<p>${esc(p.fallback)}</p></details>${sceneryLinks(p.links)}<button class="scenery-link" data-scenery-route="${code}">Zum Tour-Stopp →</button></article>`).join('');
 $('#freewareConsidered').innerHTML=SC.freewareConsidered.map(r=>`<div><strong><span class="mono">${r.codes.join(' / ')}</span> · ${esc(r.name)}</strong><p class="small">${esc(r.metrics)}</p><p>${esc(r.reason)}</p>${sceneryLinks([['Flightsim.to · Prüfquelle',r.url]])}</div>`).join('');
 $('#sceneryShortlist').innerHTML=Object.entries(SC.products).sort(([a],[b])=>SC.airports[a].order-SC.airports[b].order).map(([code,p])=>`<article class="scenery-pick"><div class="kicker">${code==='TFFJ'?'H160 · Kleiner Hersteller, starke Resonanz':'Fenix A320 · Etablierter Hersteller'}</div><div class="scenery-pick-code mono">${code}</div><h3>${esc(p.headline)}</h3><p class="scenery-product">${esc(p.developer)} · ${esc(p.name)}</p><p>${esc(p.reason)}</p><details><summary>Warum diese Ausnahme?</summary><p>${esc(p.evidence)}</p><p>${esc(p.caveat)}</p><p>${esc(p.compatibility)}</p></details><p class="scenery-fallback">${esc(p.baseline)}</p>${sceneryLinks(p.links)}<button class="scenery-link" data-scenery-route="${code}">Zum Tour-Stopp →</button></article>`).join('');
 $('#sceneryConsidered').innerHTML=Object.entries(SC.considered).map(([code,c])=>`<div><strong><span class="mono">${code}</span> · ${esc(c.candidate)}</strong><p>${esc(c.reason)}</p>${sceneryLinks(c.links)}</div>`).join('');
 $('#manufacturerPolicy').textContent=SC.manufacturerPolicy;
 $('#manufacturerRows').innerHTML=SC.manufacturers.map(m=>`<tr><td><a href="${esc(m.url)}" target="_blank" rel="noopener noreferrer"><strong>${esc(m.name)} ↗</strong></a></td><td>${m.codes.map(code=>`<button class="scenery-link mono" data-scenery="${code}">${code}</button>`).join(' ')}</td><td><p>${esc(m.note)}</p></td></tr>`).join('');
 renderScenery();
}
$('#scenerySearch').oninput=renderScenery;$('#sceneryFilter').onchange=renderScenery;$('#sceneryDepth').onchange=renderScenery;
$('#sceneryReset').onclick=()=>{$('#scenerySearch').value='';$('#sceneryFilter').value='all';$('#sceneryDepth').value='all';renderScenery()};
$('#sceneryCsv').onclick=()=>{
 const rows=[['ICAO_Ident','Airport','Kategorie','Empfehlung','Produkt_Basis','Begruendung','Hinweis','Prueftiefe','Quellen','Stand','Freeware_Downloads_ca','Freeware_Sterne','Freeware_Bewertungen','Produktversion','MSFS2024_Hinweise','Bibliotheken_Installation','Vergleich_Prueftiefe','Freeware_Kandidaten_und_Urteil','Payware_Kandidaten_und_Urteil','FSAddonCompare_ausgelesen','Weitere_Webquellen'],...SC.order.map(code=>{const g=SC.airports[code],p=sceneryProduct(code),f=SC.freeware[code],a=g.comparison;return [code,g.name,g.country,sceneryLabel(code),g.recommendation,g.reason,[g.note,p?.caveat].filter(Boolean).join(' '),g.evidence,g.links.map(l=>l[1]).join(' | '),SC.date,f?.downloads||'',f?.rating||'',f?.reviews||'',f?.version||'',p?.compatibility||'',f?.dependencies||'',a.depth,a.freeware.map(x=>x.name+' ['+x.stage+'] '+(x.metrics||'')+' — '+x.verdict+' '+x.url).join(' | '),a.payware.map(x=>x.developer+' · '+x.name+' ['+x.stage+'] '+(x.verdict||'Nicht vertieft bewertet.')+' '+(x.compatibility||'')+' '+x.url).join(' | '),a.fsacReadable?'ja':'keine auswertbare ICAO-Antwort; weitere Quellen ergänzt',a.sources.map(x=>x[1]).join(' | ')]})];
 download('Volanta-Worldtour-Szenerien.csv','\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\r\n'),'text/csv;charset=utf-8');toast('Alle 405 Szenerie-Empfehlungen exportiert');
};
