from pathlib import Path
R=Path(__file__).resolve().parent
p=R/'tour-template.html'
s=p.read_text(encoding='utf8')
def replace(old,new):
    global s
    assert old in s, old[:120]
    s=s.replace(old,new)
replace('<button data-view="highlightsView">Anflug-Highlights</button>', '<button data-view="journeyView">Alle Legs</button><button data-view="highlightsView">Anflug-Highlights</button>')
replace('Fenix A320 + Ausflüge für 245 Kategorien','Fenix A320 · H160 · Twin Otter')
replace('Eine durchgehende A320-Planungsroute.', 'Eine feste Weltreise mit drei Fluggeräten.')
replace('Die 16 ergänzenden Ausflüge bringen den Plan auf 245 Kategorien; sie sind mit Hin- und Rückflug auf einer eigenen Karte eingetragen.', 'Die 16 Ausflüge sind in die Gesamtfolge eingefügt. Unter „Alle Legs“ steht jeder Flug einschließlich Fluggerät und Rückweg; violette Linien zeigen die Ausflüge auf der Karte.')
replace('<h2>Die Legs</h2>', '<h2>Die A320-Legs</h2>')
replace('<option value="all">Gesamte Tour</option>', '<option value="all">Alle A320-Legs</option>')
replace('<div class="highlight-grid" id="highlightGrid"></div>', '<h3 class="subheading">Vier besondere Twin-Otter-Ausflüge</h3><div class="highlight-grid" id="expeditionGrid"></div><h3 class="subheading">Die großen A320-Anflüge</h3><div class="highlight-grid" id="highlightGrid"></div>')
replace('<div class="coverage-summary" id="coverageSummary"></div>', '<div class="fleet-strip" id="fleetStrip"></div><p class="small muted" id="fleetLogistics"></p><div class="coverage-summary" id="coverageSummary"></div>')
replace('ATR, Twin Otter, C172 und H125 sind Planungsprofile. Die tatsächlich installierte Variante und ihre Leistungsgrenzen bestimmen den Flug. Treibstoffversorgung an kleinen oder isolierten Plätzen ist nicht zugesichert.', 'H160 und DHC-6-300 mit Radfahrwerk sind die Ausflugsprofile. Die installierte Variante, Masse und Wetter bestimmen die Leistung. Für Antarktis und abgelegene Inseln sind die Betankungsannahmen in den Ausflugskarten Teil des Plans.')
replace('Fenix A320 CFM Sharklets · Stand', 'Fenix A320 CFM Sharklets + H160 + DHC-6-300 · Stand')
replace('Die CSV enthält die komplette Route einschließlich Anflughinweisen, Flug-/Blockzeiten, Quellen und dem lokalen Flugstand.', 'Die Gesamt-CSV enthält alle Fluggeräte in fester Reihenfolge, Hinweise, Flugzeit und lokalen Flugstand. Blockzeiten sind nur für den A320 geschätzt. Bereits geflogene, später ersetzte Direkt-Legs bleiben im Fortschrittsarchiv erhalten und zählen nicht als neue Zwischenstopps.')
replace('function renderStats(){const count=D.countries.filter(c=>c.airports.length).length;const short=D.legs.filter(l=>!l.over2h).length;const sum=D.legs.reduce((n,l)=>n+l.airMin,0);', 'function renderStats(){const count=D.countries.filter(c=>c.airports.length).length;const combined=[...D.legs,...XL];const short=combined.filter(l=>!l.over2h).length;const sum=combined.reduce((n,l)=>n+l.airMin,0);')
replace('${D.legs.length}<em> Legs</em></b><span>A320 · zusätzlich 34 Ausflugs-Legs', '${D.legs.length+XL.length}<em> Legs</em></b><span>${D.legs.length} A320 + ${XL.length} Ausflugs-Legs')
replace('A320 bis 2 h Flugzeit</div><b>${Math.round(short/D.legs.length*100)}', 'Alle Legs bis 2 h</div><b>${Math.round(short/combined.length*100)}')
replace('${D.legs.length-short} längere Legs markiert', '${combined.length-short} längere Legs markiert')
replace('A320-Flugzeit ≈', 'Gesamte Flugzeit ≈')
replace('${fmt(D.legs.reduce((n,l)=>n+l.nm,0))} NM Großkreis', '${fmt(combined.reduce((n,l)=>n+l.nm,0))} NM Großkreis')
replace("if(id==='coverageView')requestAnimationFrame(renderXMap);", "if(id==='coverageView')requestAnimationFrame(renderXMap);if(id==='journeyView')renderJourney();")
start=s.index("$('#backupExport').onclick=")
end=s.index('/*__EXCURSION_UI__*/',start)
s=s[:start]+"$('#backupImport').onclick=()=>$('#backupFile').click();\n"+s[end:]
replace('renderStats();renderHighlights();renderCoverage();renderProgress();', 'renderStats();renderHighlights();renderExpeditions();renderCoverage();renderJourney();renderProgress();')
journey='''<section class="view" id="journeyView"><div class="kicker">A320 · H160 · DHC-6-300</div><h2 class="panel-title">Deine feste Flugreihenfolge.</h2><p class="intro">Jede Zeile beginnt dort, wo die vorherige endet. Die Reihenfolgenummer zählt alle Fluggeräte; die ursprüngliche A320-Legnummer bleibt daneben erhalten. Ausflugsmaschinen stehen regional bereit und werden nicht zwischen den A320-Basen überführt.</p><div class="sectionhead"><p id="journeyTotals" class="inline-progress"></p><button id="journeyCsv" class="primary">Gesamtfolge als CSV ↓</button></div><div class="toolbar"><input id="journeySearch" type="search" placeholder="Airport, Land oder Anflug suchen …" aria-label="Gesamtreihenfolge durchsuchen"><select id="journeyFleet" aria-label="Nach Fluggerät filtern"><option value="all">Alle Fluggeräte</option><option value="A320">Fenix A320</option><option value="H160">Airbus H160</option><option value="DHC6">Twin Otter</option></select><select id="journeyStatus" aria-label="Gesamtreihenfolge nach Flugstand filtern"><option value="all">Alle Flüge</option><option value="open">Noch nicht geflogen</option><option value="done">Geflogen</option><option value="long">Über zwei Stunden</option></select></div><div class="table-wrap journey-table"><table><thead><tr><th>✓</th><th>Folge</th><th>Strecke</th><th>Fluggerät</th><th>Ziel / Kategorie</th><th>Flugzeit ≈</th><th>Details</th></tr></thead><tbody id="journeyRows"></tbody></table></div><p id="journeyCount" class="rows-count"></p><p class="small muted">Gold markiert längere Etappen. Die Verbindungslinien sind keine Navigationsverfahren; POI-Runden und Wetterumwege kommen zur Zeit hinzu. „Geflogen“ wird lokal gespeichert und bedeutet keine bestätigte Volanta-Wertung.</p><details id="retiredDetails" hidden><summary>Fortschritt früherer Direktverbindungen</summary><p class="small muted">Diese geflogenen Legs wurden durch neue Zwischenstopps ersetzt. Sie bleiben in deiner Sicherung, markieren die neuen Legs aber nicht automatisch als geflogen.</p><div id="retiredRows" class="small"></div></details></section>'''
replace('<section class="view" id="highlightsView">',journey+'\n<section class="view" id="highlightsView">')
css='''.fleet-strip{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin:25px 0 14px}.fleet-tile{padding:20px;border:1px solid var(--line);border-radius:12px;background:linear-gradient(130deg,#17352f,#101d27)}.fleet-tile:nth-child(2){background:linear-gradient(130deg,#302844,#101d27)}.fleet-tile:nth-child(3){background:linear-gradient(130deg,#443522,#101d27)}.fleet-tile b{font-size:25px;font-weight:500}.fleet-tile p{font-size:13px;color:var(--muted);margin:7px 0 0}.fleet-tile .kicker{margin-bottom:8px}.journey-table{max-height:65vh}.journey-table td:nth-child(3),.journey-table td:nth-child(6){white-space:nowrap}.journey-table tr.side td:first-child{box-shadow:inset 3px 0 var(--purple)}.fuel-note{border-left:2px solid var(--gold);padding:9px 12px;background:#30271d;border-radius:0 7px 7px 0}.exception .fuel-note{color:#e7cfac}.source-links{display:flex;gap:10px;flex-wrap:wrap;font-size:12px;margin-top:12px}#expeditionGrid{grid-template-columns:repeat(2,1fr)}#expeditionGrid .bigcode{color:var(--gold)}@media(max-width:800px){.fleet-strip,#expeditionGrid{grid-template-columns:1fr}.fleet-tile{padding:17px}.journey-table{max-height:60vh}}'''
replace('</style>',css+'</style>')
p.write_text(s,encoding='utf8')
print('Template updated')
