from pathlib import Path
R=Path(__file__).resolve().parent
p=R/'tour-template.html';s=p.read_text(encoding='utf8')
assert '__EXCURSIONS__' not in s
start=s.index('<section class="view" id="coverageView">');end=s.index('<section class="view" id="methodView">',start)
s=s[:start]+'''<section class="view" id="coverageView"><div class="kicker">A320-Welttour + 16 verbundene Ausflüge</div><h2 class="panel-title">Ein Plan für alle 245.</h2><p class="intro">Für jede Volanta-Kategorie ist jetzt eine Landestelle vorgesehen. Der Fenix verbindet die Welt; für kurze Pisten und Heliports wechselst du am Tour-Stopp das Fluggerät und kehrst anschließend dorthin zurück. Die Reihenfolge bleibt durchgehend verbunden.</p><div class="coverage-summary" id="coverageSummary"></div><div class="notice"><span class="mark">◇</span><div><strong>245 geplant bedeutet noch keine 245 bestätigten Länderpunkte.</strong> Die Vorschläge umfassen auch geschlossene oder nur im fiktiven Simulatorbetrieb genutzte Plätze. Vorab die Landestelle in MSFS 2024 prüfen; nach jedem Ausflug Volantas Erkennung kontrollieren. LLJR/Jerusalem ist in Volanta „Palestine (PS)“ zugeordnet, aber als geschlossen markiert. Dafür ist eine passende historische oder fiktive Darstellung erforderlich.</div></div><div class="x-workbench"><div id="xMapHost"><svg id="xMap" role="img" aria-label="Karte des ausgewählten Ausflugs"></svg></div><div class="x-map-info"><label for="xSelect" class="kicker">Ausflug wählen</label><select id="xSelect" aria-label="Ausflug wählen"></select><p id="xMapCaption"></p><p class="small muted">Grün: A320-Ausgangspunkt · Violett: Ausflug / Ziel. Jeder Ausflug ist eine geschlossene Schleife.</p><button class="primary" id="fullCsvExport">Alle Legs in Flugreihenfolge als CSV ↓</button></div></div><p id="xTotals" class="small muted"></p><p id="xProgress" class="inline-progress"></p><details><summary>Flugzeitschätzung der Ausflüge</summary><p id="xFormula" class="small muted"></p><p class="small muted">ATR, Twin Otter, C172 und H125 sind Planungsprofile. Die tatsächlich installierte Variante und ihre Leistungsgrenzen bestimmen den Flug. Treibstoffversorgung an kleinen oder isolierten Plätzen ist nicht zugesichert.</p></details><h3 class="subheading">16 Ausflüge. In deiner Flugreihenfolge.</h3><p class="intro" style="font-size:14px">Die Häkchen speichern jeden Hin- und Rückflug separat. „Nach Leg“ bezeichnet die unveränderte Nummer der A320-Hauptroute.</p><div class="exception-grid" id="exceptions"></div><h3 class="subheading">Vollständige Volanta-Checkliste</h3><div class="toolbar"><input id="countrySearch" type="search" placeholder="Kategorie oder Ziel suchen …" aria-label="Länderkategorien durchsuchen"><select id="countryFilter" aria-label="Kategorien filtern"><option value="all">Alle 245 Kategorien</option><option value="main">A320-Hauptroute</option><option value="special">A320-Sonderbetrieb</option><option value="exception">16 Ausflugs-Kategorien</option></select></div><div class="table-wrap coverage-table"><table><thead><tr><th>Code</th><th>Volanta-Kategorie</th><th>Planung</th><th>Landestelle / Ausflug</th></tr></thead><tbody id="countryRows"></tbody></table></div></section>
'''+s[end:]
css='''.x-workbench{display:grid;grid-template-columns:1.35fr 1fr;gap:18px;margin-top:22px}#xMapHost{height:370px;background:#102733;border:1px solid var(--line);border-radius:12px;overflow:hidden}#xMap{width:100%;height:100%;display:block}.x-map-info{padding:22px;background:var(--panel);border:1px solid var(--line);border-radius:12px}.x-map-info select{display:block;width:100%;padding:10px;margin:10px 0;background:var(--panel2);color:var(--text);border:1px solid var(--line);border-radius:7px;font-size:13px}.x-map-info p{font-size:14px}.exception{background:#141e28;border-color:#3d3b51}.exception .kicker{font-size:11px;margin-bottom:10px}.exception .tags{margin:8px 0}.exception h3{font-size:23px}.exception p{color:#bbc9d1}.exception .side-trip{color:var(--purple);font-size:14px}.exception .xverify{border-left:2px solid var(--teal);padding-left:10px;color:#bfdbd0}.xlegs{border-top:1px solid var(--line);border-bottom:1px solid var(--line);margin:16px 0;padding:8px 0}.xlegs label{display:grid;grid-template-columns:20px 1fr auto;align-items:center;gap:8px;padding:6px 0;font-size:12px;cursor:pointer}.xlegs input{accent-color:var(--purple);width:16px;height:16px}.exception .card-footer{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.exception summary{font-size:13px;color:var(--muted);cursor:pointer}@media(max-width:900px){.x-workbench{grid-template-columns:1fr}}@media(max-width:430px){.xlegs label{grid-template-columns:20px 1fr}.xlegs label span:last-child{grid-column:2}.x-map-info{padding:16px}}'''
s=s.replace('</style>',css+'</style>',1)
s=s.replace('<script id="briefingData" type="application/json">__BRIEFINGS__</script>','<script id="briefingData" type="application/json">__BRIEFINGS__</script><script id="excursionData" type="application/json">__EXCURSIONS__</script>')
s=s.replace("localStorage.setItem(storageKey,JSON.stringify({done:[...state.done]}))}catch(e){storageOK=false}\nfunction toast", "localStorage.setItem(storageKey,JSON.stringify({...saved,done:[...state.done]}))}catch(e){storageOK=false}\nfunction toast")
old="function save(){try{localStorage.setItem(storageKey,JSON.stringify({done:[...state.done]}))}catch(e){storageOK=false}renderProgress()}"
assert old in s;s=s.replace(old,'function save(){saveAll()}')
s=s.replace("if(id==='tourView')requestAnimationFrame(renderMap);", "if(id==='tourView')requestAnimationFrame(renderMap);if(id==='coverageView')requestAnimationFrame(renderXMap);")
s=s.replace('<b>${count}<em> / 245</em></b><span>16 separat · inkl. Sonderbetrieb</span>','<b>245<em> / 245</em></b><span>229 A320 + 16 Ausflüge geplant*</span>')
s=s.replace('<span>${D.chapters.length} Kapitel · ${Object.keys(A).length} Airports</span>','<span>A320 · zusätzlich 34 Ausflugs-Legs</span>')
s=s.replace('<div class="kicker">Bis 2 h Flugzeit</div>','<div class="kicker">A320 bis 2 h Flugzeit</div>')
s=s.replace('<div class="kicker">Gesamte Flugzeit ≈</div>','<div class="kicker">A320-Flugzeit ≈</div>')
# Remove superseded definitions so each function has a single source of truth.
s='\n'.join(line for line in s.split('\n') if not line.startswith(('function renderCoverage(){','function renderCountryRows(){')))
s=s.replace("renderStats();renderHighlights();renderCoverage();renderProgress();setChapter('01');", "/*__EXCURSION_UI__*/\nrenderStats();renderHighlights();renderCoverage();renderProgress();setChapter('01');")
s=s.replace('Fenix A320 · CFM · Sharklets</div></div></header>','Fenix A320 + Ausflüge für 245 Kategorien</div></div></header>')
s=s.replace('Eine Sicherung exportiert die erledigten Legs und lässt sich später wieder einlesen.','Eine Sicherung exportiert die erledigten A320- und Ausflugs-Legs und lässt sich später wieder einlesen. Frühere Sicherungen der 403 A320-Legs bleiben kompatibel.')
p.write_text(s,encoding='utf8')
print('Updated HTML template')
